name: buildingblocks
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
  say-goodbye:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye!"