name: 02 - Work Flow Events
on:
    push:
    pull_request: 
    schedule:
        - cron: "15 4,5 * * *"
    workflow_dispatch: 

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the Trigger
        run: echo "event name is:" ${{ github.event_name }} 


