name: 02 - Work Flow Events
on:
    workflow_dispatch: 

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the Trigger
        run: echo "event name is:" ${{ github.event_name }} 


