name: 09 - Using Functions
on: 
  pull_request: 
  workflow_dispatch: 

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: "Sleep for 20 seconds"
              run: sleep 20
            - name: "Failing step"
              run: |
                echo 'This sgep fails on purpose'
                exit 1
            - name: 'I will be skipped'
              run: echo " I will print if the previous step fails"
            - name: 'I will execute'
              run: echo "I will print if any previous step fails."
            - name: 'I will execute'
              run: echo "I will always print, except when the workflow is cancelled."
            - name: " I will execute when cancelled"
              run: echo " i will print only when teh workflow is cancelled"
