name: 15 - Working with Matrices
on:
    workflow_dispatch: 
jobs:
     backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        strategy:
            fail-fast: true
            matrix:  
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      tag: linux
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: "experimental"
        runs-on: ${{ matrix.os }}
        steps:
            - name: setup Node
              uses: actions/setup-node@v4
              with:
                node: ${{ matrix.node-version }}
            - name: fail if experimental
              if: matrix.tag == 'experimental'
              run: exit 1
            - name: Upload Test Results
              run: |
               echo "Uploading test results"



                