name: 17 - 3 - Custom Actions - Docker
on: 
    workflow_dispatch: 
        inputs:
            url:
                type: choice
                options:
                    - 'https://bbc.co.uk'
                    - 'https://www.googlereerververv.com'
                    - 'me.me'
            max_trials:
                description: 'Maximum trials until action fails'
                default: '10'
                required: false
            delay:
                description: 'Delay in seconds between trials'
                default: '5'
                required: false


jobs:
    ping_url:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Code
              uses: actions/Checkout@v4
            - name: Ping url
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{ inputs.url }}
                max_trials: ${{ inputs.max_trials}}
                delay: ${{ inputs.delay }}
                  

