name: 17 - 3 - Custom Actions - Docker
on: 
    workflow_dispatch: 
        inputs:
            url:
                type: string
                default: 'https://www.google.com'

jobs:
    ping_url:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Code
              uses: actions/Checkout@v4
            - name: Ping url
              uses: ./.github/actions/docker-ping-url
              